export const ALLOWED_LOG_PACKAGES = [
    'api',
    'backend',
    'component',
    'config',
    'controller',
    'frontend',
    'hook',
    'logger',
    'middleware',
    'page',
    'route',
    'service',
    'state',
    'util',
];
